GraSP:
  exp_name: "with momentum"
  network: ttm
  depth: 2
  dataset: mnist
  batch_size: 64
  epoch: 10
  learning_rate: 0.001
  weight_decay: 1e-4
  exception: -1
  iterations: 1
  normalize: false
  target_ratio: 0.9
  pruner: False
  pruner_file: False
  num_classes: 10
  samples_per_class: 10
  samples_batches: 5
  num_iters: 1

optimizer:
  name: ADAM
  grad_sparsity: 0

scheduler:
  name: 'PresetLRScheduler'
  gamma: 0.985
  lr_schedule: {0: 1,
                10: 0.1}

pretrained:
  incre: True
  load_model_path: './runs/pruning/mnist/ttm/ZO_SCD_batch/False/scratch_two_bz64_grad0.5_lr_0.01/20230329-080506/run_None/finetune_mnist_ttm2_r0.9_it0_best.pth.tar'
  pruned: False

run:
  runs: None
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

model:
  tensor_type: 'TensorTrainMatrix'
  max_rank: 4
  tensorized: 'TensorizedLinear_module'

checkpoint:
  save_model: "model/MNIST_notensor_2layers_FP32"
  save_mode: "best"
  proj_share_weight: 1
  label_smoothing: 1
