GraSP:
  exp_name: "MNIST_ttm_mix_gamma08_switch10"
  network: ttm
  depth: 2
  dataset: mnist
  batch_size: 64
  epoch: 40
  learning_rate: 0.005
  weight_decay: 1e-4
  exception: -1
  iterations: 1
  normalize: false
  target_ratio: 0.99
  pruner: False
  pruner_file: False
  num_classes: 10
  samples_per_class: 10
  samples_batches: 5
  num_iters: 1

optimizer:
  name: ZO_mix
  sigma: 0.1
  n_sample: 10
  signSGD: True
  layer_by_layer: False
  debug: False
  switch_epoch: 10
  SCD_lr: 0.001
  grad_sparsity: 0.5
  opt_layers_strs: 'TensorizedLinear_module'
  comment: 'signSGD + SCD'

scheduler:
  name: ZO_mix
  gamma: 0.8
  lr_schedule: {10: 1,
                20: 0.1}

run:
  runs: None
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

model:
  tensor_type: 'TensorTrainMatrix'
  max_rank: 4
  tensorized: 'TensorizedLinear_module'

checkpoint:
  save_model: "model/MNIST_notensor_SCD"
  save_mode: "best"
  proj_share_weight: 1
  label_smoothing: 1
