GraSP:
  exp_name: "lr0.01_preset_grad0"
  network: ttm
  depth: 2
  dataset: mnist
  batch_size: 64
  epoch: 20
  learning_rate: 0.01
  weight_decay: 1e-4
  exception: -1
  iterations: 1
  normalize: false
  target_ratio: 0.90
  pruner: False
  pruner_file: False
  num_classes: 10
  samples_per_class: 10
  samples_batches: 5
  num_iters: 1

optimizer:
  name: ZO_SCD_mask
  grad_sparsity: 0

scheduler:
  name: 'PresetLRScheduler'
  lr_schedule: {0: 1,
                2: 0.1,
                5: 0.01}

# scheduler:
#   name: 'ExponentialLR'
#   gamma: 0.8

run:
  runs: None
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

pretrained:
  incre: False
  load_model_path: 'model/ATIS_GraSP_FO_95_best.chkpt'
  pruner: GraSP_attn

model:
  tensor_type: 'TensorTrainMatrix'
  max_rank: 4
  tensorized: 'TensorizedLinear_module'

checkpoint:
  save_model: "model/MNIST_notensor_SCD"
  save_mode: "best"
  proj_share_weight: 1
  label_smoothing: 1
