GraSP:
  exp_name: "incre_bz1024_lr0.0001_K10000_exp85"
  network: ttm
  depth: 2
  dataset: mnist
  batch_size: 1024
  epoch: 30
  learning_rate: 0.0001
  weight_decay: 1e-4
  exception: -1
  iterations: 1
  normalize: false
  target_ratio: 0.99
  pruner: False
  pruner_file: False
  num_classes: 10
  samples_per_class: 10
  samples_batches: 5
  num_iters: 1

optimizer:
  name: ZO_SGD_mask
  sigma: 0.1
  n_sample: 1000000
  signSGD: False
  layer_by_layer: False
  opt_layers_strs: 'TensorizedLinear_module'
  debug: True

scheduler:
  name: 'PresetLRScheduler'
  lr_schedule: {0: 1,
                5: 0.1,
                10: 0.01}

scheduler:
  name: 'ExponentialLR'
  gamma: 0.85

run:
  runs: None
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

pretrained:
  incre: True
  load_model_path: './runs/pruning/mnist/ttm/ADAM/MNIST_ttm_FO_adam/20230308-062638/run_None/finetune_mnist_ttm2_r0.9_it0_best.pth.tar'
  # load_model_path: './runs/pruning/mnist/ttm/ZO_SGD_mask/MNIST_ttm_sgd_exp085_e15/20230307-075309/run_None/finetune_mnist_ttm2_r0.99_it0_best.pth.tar'
  pruned: False

model:
  tensor_type: 'TensorTrainMatrix'
  max_rank: 4
  tensorized: 'TensorizedLinear_module'

checkpoint:
  save_model: "model/MNIST_notensor_SCD"
  save_mode: "best"
  proj_share_weight: 1
  label_smoothing: 1
