GraSP:
  exp_name: "ATIS_GraSP_SCD_95_incre"
  network: attn
  depth: 2
  dataset: ATIS
  batch_size: 64
  epoch: 30
  learning_rate: 0.001
  weight_decay: 1e-4
  exception: -1
  iterations: 1
  normalize: false
  target_ratio: 0.95
  pruner: False
  pruner_file: False
  num_classes: 21
  samples_per_class: 10
  samples_batches: 5
  num_iters: 1

optimizer:
  name: ZO_SCD_mask
  grad_sparsity: 0.9

scheduler:
  name: 'PresetLRScheduler'
  gamma: 0.985
  lr_schedule: {0: 1,
                5: 0.1,
                10: 0.01}

pretrained:
  incre: True
  load_model_path: 'model/ATIS_GraSP_FO_95_best.chkpt'
  pruner: GraSP_attn

run:
  runs: None
  n_epochs: 100
  batch_size: 32
  use_cuda: 1
  gpu_id: 0
  deterministic: 1
  log_interval: 200
  train_noise: 0

model:
  tensorized: None

checkpoint:
  save_model: "model/ATIS_notensor_2layers_FP32/GraSP_95"
  save_mode: "best"
  proj_share_weight: 1
  label_smoothing: 1
